export const FIND_APPLICATION_BY_SHORTCODE_REQUEST = 'FIND APPLICATION BY SHORTCODE REQUEST';
export const FIND_APPLICATION_BY_SHORTCODE_SUCCESS = 'FIND APPLICATION BY SHORTCODE SUCCESS';
export const FIND_APPLICATION_BY_SHORTCODE_FAILED  = 'FIND APPLICATION BY SHORTCODE FAILED';