export const FETCH_APPLICATION_BY_TOKEN_REQUEST = 'FETCH APPLICATION BY TOKEN REQUEST';
export const FETCH_APPLICATION_BY_TOKEN_SUCCESS = 'FETCH APPLICATION BY TOKEN SUCCESS';
export const FETCH_APPLICATION_BY_TOKEN_FAILED  = 'FETCH APPLICATION BY TOKEN FAILED';