// findApplicationByShortcode
export const FIND_APPLICATION_BY_SHORTCODE_REQUEST = 'FIND APPLICATION BY SHORTCODE REQUEST';
export const FIND_APPLICATION_BY_SHORTCODE_SUCCESS = 'FIND APPLICATION BY SHORTCODE SUCCESS';
export const FIND_APPLICATION_BY_SHORTCODE_FAILED  = 'FIND APPLICATION BY SHORTCODE FAILED';

// validateSignInDetails
export const VALIDATE_SIGN_IN_DETAILS_REQUEST = 'VALIDATE SIGN IN DETAILS REQUEST';
export const VALIDATE_SIGN_IN_DETAILS_SUCCESS = 'VALIDATE SIGN IN DETAILS SUCCESS';
export const VALIDATE_SIGN_IN_DETAILS_FAILED  = 'VALIDATE SIGN IN DETAILS FAILED';